import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.scss';
import Layout from '@/Components/Layout/Layout';

const inter = Inter({ subsets: ['latin', 'cyrillic'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Graphi-ql Playground</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={`${styles.main} ${inter.className}`}>
          <div className={styles.description}>Home Page</div>
        </main>
      </Layout>
    </>
  );
}
