import Head from 'next/head';
import { ReactElement } from 'react';
import { CourseSection } from '@/Components/CourseSection';
import { TeamSection } from '@/Components/TeamSection';

function Home(): ReactElement {
  return (
    <>
      <Head>
        <title>Graphi-ql Playground</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <CourseSection />
        <TeamSection />
      </>
    </>
  );
}

export default Home;
